server:
  port: 8103

spring:
  application:
    name: study-order

study:
  swagger:
    instance:
      api-info:
        title: 订单
        description: 订单描述
        default-include-pattern: /rest/.*

